### ISSUE TITLE
information

### ISSUE THREAD

**Issue by turkfuat** [koriavinash1/Fetal-Brain-Segmentation#1]
hello
how do I run this code for kidney tumors. I am new to deep learning. Could you help. What exactly do I need to do?

thanks.

**Comment by sureshkumar0707** [comment]
@turkfuat Can you able to run the code without any errors ??? 

I got struck in the - Folder Path ??? 

root = './raw_data/'
folders = ['Normal01/', 'Normal02/']
dest = './processed_data/hdf5_file/'

if not os.path.exists(dest):
    os.makedirs(dest)
vols, segs = [], []
for folder in folders:
    folder_path = os.path.join(root, folder)
    for f in next(os.walk(**folder_path**))[2]:
        vols.append(os.path.join(folder_path, f))
    for s in next(os.walk(os.path.join(folder_path, "ManualSegmentation")))[2]:
        segs.append(os.path.join(os.path.join(folder_path, "ManualSegmentation"), s))
vols.sort()
segs.sort()
print(len(vols))
print(len(segs))

**Comment by koriavinash1** [comment]
@turkfuat  yoy can use any data for training, just generate hdf5 files with your data using Generate_Processed_Data.ipynb. followed by training the model. 

If you find any errors or any specific questions please let me know

**Comment by koriavinash1** [comment]
@sureshkumar0707 can you please paste the exact error here?, so that I can help

**Comment by sureshkumar0707** [comment]
I have processed all the steps in the Generate_Procesed_Data.ipynb and generated the .csv file

I have some doubts,

**Doubt 1:**

I got predictions for 17 samples in the Normal01 and Normal02 folder.
--
You have included Manual Segmentation folder which contains Mask file for each samples of .nii file.

If I want to process my own input, How can I create mask file for my input?

**Doubt 2:**
I finally executed the runner.py, I faced with few errors. I will paste the code below. 

I executed the code in the anaconda prompt using the command: py runner.py

I faced the following issues:

...
Total Number of Trainable Parameters: 1550914
Preparing the estimator..
batch size : 16
Initialising data loader ...
Traceback (most recent call last):
  File "runner.py", line 50, in <module>
    config = conf
  File "C:\Users\SKP\Prac2\5-15-2019\Pro1\estimator.py", line 30, in __init__
...
FileNotFoundError: File b'../train_test_split.csv' does not exist
 Thread exited

Inside the data_loader.py

I have given the data path as,
data_path = "123/train_test_split.csv"

and I keep the file inside the folder, But still I face error.

Kindly resolve bro.

**Comment by koriavinash1** [comment]
@sureshkumar0707  getWeightMap(.) function will return the required weight map. Masks are basically your gt for training if you want to use your own data for training you need to manually annotate it or use some pre-trained model to get mask.  

when you run Generate_Procesed_Data.ipynb it'll generate train_test_split.csv in ./processed_data folder, before running runner.py just move train_test_split.csv outside src folder. 

Hope this solves your issue ...

**Comment by sureshkumar0707** [comment]
@koriavinash1 Thanks. I solved the issue.

Identified an error at the next step.

I placed the Best Model Files in the following...

In the folder.. ???  >> models/U-NET__DiceLoss/models/ <4 files from Best model folder>

Instructions for updating:
Use tf.cast instead.
Total Number of Trainable Parameters: 1550914
Preparing the estimator..
batch size : 16
Initialising data loader ...
Traceback (most recent call last):
  File "runner.py", line 50, in <module>
    config = conf
  File "C:\Users\SKP\Prac2\5-15-2019\Pro1\src\estimator.py", line 30, in __init__
    self.data_iterator = ITERATOR(self.conf.data_folder, mode = 'train',        batch_size = self.conf.batch_size, num_threads=1)
  File "C:\Users\SKP\Prac2\5-15-2019\Pro1\src\data_loader.py", line 103, in __init__
    self.getFilePaths(data_folder_path)
  File "C:\Users\SKP\Prac2\5-15-2019\Pro1\src\data_loader.py", line 113, in getFilePaths
    self.train_fls = np.squeeze(train_valid_paths[train_valid_paths['Training']]['Slice Path'].values()).tolist()
TypeError: 'numpy.ndarray' object is not callable
 Thread exited

(base) C:\Users\SKP\Prac2\5-15-2019\Pro1\src>

**Comment by koriavinash1** [comment]
@sureshkumar0707 can you please share the .csv generated?

**Comment by sureshkumar0707** [comment]
Thanks Bro, I resolved the error.

Generated CSV file from Process_data folder.

**https://drive.google.com/open?id=1ntQ-UnE4a5kwEZAR3ir-IIDQy--mRpTW**

--

Can you send the link of the dataset source website?  
So that I can download more volumes of fetal brain for my testing.

**Comment by sureshkumar0707** [comment]
I have updated the Issue bro.

**Comment by sureshkumar0707** [comment]
> @sureshkumar0707 can you please share the .csv generated?

I resolved the error bro.

**Comment by koriavinash1** [comment]
@sureshkumar0707 what was the error?

**Comment by sureshkumar0707** [comment]
Doubt 1: Can you provide the link of the website about the Dataset. I need
some meta data.

Error 1. 

Total Number of Trainable Parameters: 1550914
Preparing the estimator..
batch size : 16
Initialising data loader ...
Traceback (most recent call last):
  File "runner.py", line 50, in <module>
    config = conf
  File "C:\Users\SKP\Prac2\5-15-2019 - Best Day\Pro1\src\estimator.py", line 30, in __init__
    self.data_iterator = ITERATOR(self.conf.data_folder, mode = 'train',        batch_size = self.conf.batch_size, num_threads=1)
  File "C:\Users\SKP\Prac2\5-15-2019 - Best Day\Pro1\src\data_loader.py", line 103, in __init__
    self.getFilePaths(data_folder_path)
  File "C:\Users\SKP\Prac2\5-15-2019 - Best Day\Pro1\src\data_loader.py", line 113, in getFilePaths
    self.train_fls = np.squeeze(train_valid_paths[train_valid_paths['Training']]['Slice Path'].values()).tolist()
TypeError: 'numpy.ndarray' object is not callable
 Thread exited

**Comment by turkfuat** [comment]
THANK YOU
I solved my problem

________________________________
Gönderen: sureshkumar0707 <notifications@github.com>
Gönderildi: 28 Mayıs 2019 Salı 20:22
Kime: koriavinash1/Fetal-Brain-Segmentation
Bilgi: turkfuat; Mention
Konu: Re: [koriavinash1/Fetal-Brain-Segmentation] information (#1)

Error 1. numpy.ndarray object was not callable.

Doubt 1: Can you provide the link of the website about the Dataset. I need
some meta data.

**Comment by turkfuat** [comment]
thank you
I solved my problem

________________________________
Gönderen: sureshkumar0707 <notifications@github.com>
Gönderildi: 27 Mayıs 2019 Pazartesi 11:50
Kime: koriavinash1/Fetal-Brain-Segmentation
Bilgi: turkfuat; Mention
Konu: Re: [koriavinash1/Fetal-Brain-Segmentation] information (#1)


@sureshkumar0707<https://github.com/sureshkumar0707> can you please share the .csv generated?

I resolved the error bro.
